routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::resource('/pengguna', UserController::class);
Route::resource('/user', UserController::class);
Route::resource('/informasi', InformasiController::class);
Route::resource('/ormawa', OrmawaController::class);
Route::resource('/pendaftaran', PendaftaranController::class);
Route::resource('/pendaftaran/{pendaftaran_id}/prestasi', PrestasiController::class);
Route::resource('/pendaftaran/{pendaftaran_id}/pengalaman', PengalamanController::class);


Route::get('/pendaftaran/{id}/changestatus', 'PendaftaranController@changeStatus')->name('changestatus');

Route::get('/export/{surat}/{type}/{id}', 'PendaftaranController@exportPdf')->name('export');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('/get-status', 'HomeController@getStatus')->name('get-status');
Route::get('/get-type', 'HomeController@getType')->name('get-type');

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
    <div class="grid grid-cols-12 gap-6">
    <div class="col-span-12 xxl:col-span-9 grid grid-cols-12 gap-6">
                    <!-- BEGIN: General Report -->
                    <div class="col-span-12 mt-8">
                        <div class="intro-y flex items-center h-10">
                            <h2 class="text-lg font-medium truncate mr-5">
                                General 
                            </h2>
                        </div>
                        <div class="grid grid-cols-12 gap-6 mt-5">
                            <div class="col-span-12 sm:col-span-6 xl:col-span-3 intro-y">
                                <div class="report-box zoom-in">
                                    <div class="box p-5">
                                        <div class="flex">
                                            <i data-feather="clipboard" class="report-box__icon text-theme-10"></i> 
                                            <div class="ml-auto">
                                            </div>
                                        </div>
                                        <div class="text-3xl font-bold leading-8 mt-6">{{count($data['pendaftaran'])}}</div>
                                        <div class="text-base text-gray-600 mt-1">Total Pendaftaran</div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-span-12 sm:col-span-6 xl:col-span-3 intro-y">
                                <div class="report-box zoom-in">
                                    <div class="box p-5">
                                        <div class="flex">
                                            <i data-feather="info" class="report-box__icon text-theme-11"></i> 
                                            <div class="ml-auto">
                                            </div>
                                        </div>
                                        <div class="text-3xl font-bold leading-8 mt-6">{{count($data['informasi'])}}</div>
                                        <div class="text-base text-gray-600 mt-1">Total Informasi</div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-span-12 sm:col-span-6 xl:col-span-3 intro-y">
                                <div class="report-box zoom-in">
                                    <div class="box p-5">
                                        <div class="flex">
                                            <i data-feather="slack" class="report-box__icon text-theme-12"></i> 
                                            <div class="ml-auto">
                                            </div>
                                        </div>
                                        <div class="text-3xl font-bold leading-8 mt-6">{{count($data['ormawa'])}}</div>
                                        <div class="text-base text-gray-600 mt-1">Total Ormawa</div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-span-12 sm:col-span-6 xl:col-span-3 intro-y">
                                <div class="report-box zoom-in">
                                    <div class="box p-5">
                                        <div class="flex">
                                            <i data-feather="users" class="report-box__icon text-theme-9"></i> 
                                            <div class="ml-auto">
                                            </div>
                                        </div>
                                        <div class="text-3xl font-bold leading-8 mt-6">{{count($data['user'])}}</div>
                                        <div class="text-base text-gray-600 mt-1">Total User</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- END: General Report -->
                    <!-- BEGIN: Weekly Top Seller -->
                    <div class="col-span-12 sm:col-span-6 lg:col-span-3 mt-8">
                        <div class="intro-y flex items-center h-10">
                            <h2 class="text-lg font-medium truncate mr-5">
                                Status Pendaftaran
                            </h2>
                            <a href="{{url('/pendaftaran')}}" class="ml-auto text-theme-1 truncate">See all</a> 
                        </div>
                        <div class="intro-y box p-5 mt-5">
                            <canvas class="mt-3" id="report-pie-chart" height="280"></canvas>
                            <div class="mt-8">
                                @foreach($status as $st)
                                <div class="flex items-center">
                                    <div class="w-2 h-2 bg-{{$st['color_name']}}-500 rounded-full mr-3"></div>
                                    <span class="truncate">{{$st['status']}}</span> 
                                    <div class="h-px flex-1 border border-r border-dashed border-gray-300 mx-3 xl:hidden"></div>
                                    <span class="font-medium xl:ml-auto">{{$st['persentase']}}%</span> 
                                </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                    <!-- END: Weekly Top Seller -->
                    <!-- BEGIN: Sales Report -->
                    <div class="col-span-12 sm:col-span-6 lg:col-span-3 mt-8">
                        <div class="intro-y flex items-center h-10">
                            <h2 class="text-lg font-medium truncate mr-5">
                                Tipe Pendaftar
                            </h2>
                            <a href="{{url('/pendaftaran')}}" class="ml-auto text-theme-1 truncate">See all</a> 
                        </div>
                        <div class="intro-y box p-5 mt-5">
                            <canvas class="mt-3" id="report-donut-chart" height="280"></canvas>
                            <div class="mt-8">
                                <div class="flex items-center">
                                    <div class="w-2 h-2 bg-theme-11 rounded-full mr-3"></div>
                                    <span class="truncate">Bem</span> 
                                    <div class="h-px flex-1 border border-r border-dashed border-gray-300 mx-3 xl:hidden"></div>
                                    <span class="font-medium xl:ml-auto">{{$type[0]}}</span> 
                                </div>
                                <div class="flex items-center mt-4">
                                    <div class="w-2 h-2 bg-theme-1 rounded-full mr-3"></div>
                                    <span class="truncate">Balma</span> 
                                    <div class="h-px flex-1 border border-r border-dashed border-gray-300 mx-3 xl:hidden"></div>
                                    <span class="font-medium xl:ml-auto">{{$type[1]}}</span> 
                                </div>
                                <div class="flex items-center mt-4">
                                    <div class="w-2 h-2 bg-theme-12 rounded-full mr-3"></div>
                                    <span class="truncate">Hima</span> 
                                    <div class="h-px flex-1 border border-r border-dashed border-gray-300 mx-3 xl:hidden"></div>
                                    <span class="font-medium xl:ml-auto">{{$type[2]}}</span> 
                                </div>
                                <div class="flex items-center mt-4">
                                    <div class="w-2 h-2 bg-gray-500 rounded-full mr-3"></div>
                                    <span class="truncate">Belum memilih</span> 
                                    <div class="h-px flex-1 border border-r border-dashed border-gray-300 mx-3 xl:hidden"></div>
                                    <span class="font-medium xl:ml-auto">{{$type[3]}}</span> 
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- END: Sales Report -->
                    <!-- BEGIN: Weekly Best Sellers -->
                    <div class="col-span-12 xl:col-span-6 mt-8">
                        <div class="intro-y flex items-center h-10">
                            <h2 class="text-lg font-medium truncate mr-5">
                                Pendaftar Terbaru
                            </h2>
                        </div>
                        <div class="mt-5">
                            @foreach($user_new as $user)
                            <div class="intro-y">
                                <div class="box px-4 py-4 mb-3 flex items-center zoom-in">
                                    <div class="w-10 h-10 flex-none image-fit rounded-md overflow-hidden">
                                        <img alt="Midone Tailwind HTML Admin Template" src="{{!empty($user->img_profile) ? url('/upload/'.$user->img_profile) : url('dist/images/user-default.png') }}">
                                    </div>
                                    <div class="ml-4 mr-auto">
                                        <div class="font-medium">{{$user->name}}</div>
                                        <div class="text-gray-600 text-xs">{{date('d M Y ', strtotime($user->created_at))}}</div>
                                    </div>
                                </div>
                            </div>
                            @endforeach
                            <a href="{{url('/pengguna')}}" class="intro-y w-full block text-center rounded-md py-4 border border-dotted border-theme-15 text-theme-16">View All</a> 
                        </div>
                    </div>
                    <!-- END: Weekly Best Sellers -->
                </div>
    </div>
</div>
@endsection

resources/views/dashboard_user.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
        <!-- END: Top Bar -->
        <div class="intro-y flex items-center mt-8">
            <h2 class="text-lg font-medium mr-auto">
                Profile Layout
            </h2>
        </div>
        <!-- BEGIN: Profile Info -->
        <div class="intro-y box px-5 pt-5 mt-5">
            <div class="flex flex-col lg:flex-row border-b border-gray-200 pb-5 -mx-5">
                <div class="flex flex-1 px-5 items-center justify-center lg:justify-start">
                    <div class="w-20 h-20 sm:w-24 sm:h-24 flex-none lg:w-32 lg:h-32 image-fit relative">
                        <img alt="Midone Tailwind HTML Admin Template" class="rounded-full" src="{{!empty(auth()->user()->img_profile) ? url('/upload/'.auth()->user()->img_profile) : url('dist/images/user-default.png')}}">
                    </div>
                    <div class="ml-5">
                        <div class="w-24 sm:w-40 truncate sm:whitespace-normal font-medium text-lg">{{auth()->user()->name}}</div>
                        <div class="text-gray-600">Pengguna</div>
                    </div>
                </div>
                <div class="flex mt-6 lg:mt-0 items-center lg:items-start flex-1 flex-col justify-center text-gray-600 px-5 border-l border-r border-gray-200 border-t lg:border-t-0 pt-5 lg:pt-0">
                    <div class="truncate sm:whitespace-normal flex items-center"> <i data-feather="mail" class="w-4 h-4 mr-2"></i> {{auth()->user()->email}} </div>
                    <div class="truncate sm:whitespace-normal flex items-center mt-3"> <i data-feather="phone" class="w-4 h-4 mr-2"></i> {{!empty(auth()->user()->pendaftaran->no_hp) ? auth()->user()->pendaftaran->no_hp : 'Belum diisi'}} </div>
                    <div class="truncate sm:whitespace-normal flex items-center mt-3"> <i data-feather="map-pin" class="w-4 h-4 mr-2"></i> {{!empty(auth()->user()->pendaftaran->no_hp) ? auth()->user()->pendaftaran->alamat : 'Belum diisi'}} </div>
                </div>
                <div class="mt-6 lg:mt-0 flex-1 flex items-center justify-center px-5 border-t lg:border-0 border-gray-200 pt-5 lg:pt-0">
                    <div class="text-center rounded-md w-20 py-3">
                        <div class="font-semibold text-theme-1 text-lg">{{ucfirst(auth()->user()->pendaftaran->status)}}</div>
                        <div class="text-gray-600">Pendaftaran</div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END: Profile Info -->
        <div class="tab-content mt-5">
            <div class="tab-content__pane active" id="profile">
                <div class="grid grid-cols-12 gap-6">
                    <!-- BEGIN: Latest Uploads -->
                    <div class="col-span-12 sm:col-span-6 lg:col-span-6">
                        <div class="intro-y box col-span-12 lg:col-span-6">
                            <div class="flex items-center px-5 py-5 sm:py-3 border-b border-gray-200">
                                <h2 class="font-medium text-base mr-auto">
                                    File Upload
                                </h2>
                                <div class="dropdown relative ml-auto sm:hidden">
                                    <a class="dropdown-toggle w-5 h-5 block" href="javascript:;"> <i data-feather="more-horizontal" class="w-5 h-5 text-gray-700"></i> </a>
                                    <div class="dropdown-box mt-5 absolute w-40 top-0 right-0 z-10">
                                        <div class="dropdown-box__content box p-2"> <a href="javascript:;" class="block p-2 transition duration-300 ease-in-out bg-white hover:bg-gray-200 rounded-md">All Files</a> </div>
                                    </div>
                                </div>
                            </div>
                            <div class="p-5">
                                
                                <div class="flex items-center">
                                    <div class="file"> <a href="" class="w-12 file__icon file__icon--directory"></a> </div>
                                    <div class="ml-4">
                                        <a class="font-medium" href="">Foto 3 x 4</a> 
                                        <div class="text-{{!empty(auth()->user()->pendaftaran->foto) ? 'green' : 'red'}}-600 text-xs">{{!empty(auth()->user()->pendaftaran->foto) ? 'Sudah' : 'Belum'}} Upload</div>
                                    </div>
                                </div>
                                <div class="flex items-center mt-5">
                                    <div class="file"> <a href="" class="w-12 file__icon file__icon--empty-directory"></a> </div>
                                    <div class="ml-4">
                                        <a class="font-medium" href="">Tanda Tangan</a> 
                                        <div class="text-{{!empty(auth()->user()->pendaftaran->tanda_tangan) ? 'green' : 'red'}}-600 text-xs">{{!empty(auth()->user()->pendaftaran->tanda_tangan) ? 'Sudah' : 'Belum'}} Upload</div>
                                    </div>
                                </div>
                                <div class="flex items-center mt-5">
                                    <div class="file"> <a href="" class="w-12 file__icon file__icon--empty-directory"></a> </div>
                                    <div class="ml-4">
                                        <a class="font-medium" href="">Tanda Tangan Orang Tua</a> 
                                        <div class="text-{{!empty(auth()->user()->pendaftaran->tanda_tangan_orangtua) ? 'green' : 'red'}}-600 text-xs">{{!empty(auth()->user()->pendaftaran->tanda_tangan_orangtua) ? 'Sudah' : 'Belum'}} Upload</div>
                                    </div>
                                </div>
                                <div class="flex items-center mt-5">
                                    <div class="file"> <a href="" class="w-12 file__icon file__icon--empty-directory"></a> </div>
                                    <div class="ml-4">
                                        <a class="font-medium" href="">Surat Dukungan</a> 
                                        <div class="text-{{!empty(auth()->user()->pendaftaran->surat_dukungan) ? 'green' : 'red'}}-600 text-xs">{{!empty(auth()->user()->pendaftaran->surat_dukungan) ? 'Sudah' : 'Belum'}} Upload</div>
                                    </div>
                                </div>
                                <div class="flex items-center mt-5">
                                    <div class="file"> <a href="" class="w-12 file__icon file__icon--empty-directory"></a> </div>
                                    <div class="ml-4">
                                        <a class="font-medium" href="">KRS Terakhir</a> 
                                        <div class="text-{{!empty(auth()->user()->pendaftaran->krs_terakhir) ? 'green' : 'red'}}-600 text-xs">{{!empty(auth()->user()->pendaftaran->krs_terakhir) ? 'Sudah' : 'Belum'}} Upload</div>
                                    </div>
                                </div>
                                <div class="flex items-center mt-5">
                                    <div class="file"> <a href="" class="w-12 file__icon file__icon--empty-directory"></a> </div>
                                    <div class="ml-4">
                                        <a class="font-medium" href="">KHS Terakhir</a> 
                                        <div class="text-{{!empty(auth()->user()->pendaftaran->khs_terakhir) ? 'green' : 'red'}}-600 text-xs">{{!empty(auth()->user()->pendaftaran->khs_terakhir) ? 'Sudah' : 'Belum'}} Upload</div>
                                    </div>
                                </div>
                                <div class="flex items-center mt-5">
                                    <div class="file"> <a href="" class="w-12 file__icon file__icon--empty-directory"></a> </div>
                                    <div class="ml-4">
                                        <a class="font-medium" href="">Sertifikat Kepengurusan Ormawa</a> 
                                        <div class="text-{{!empty(auth()->user()->pendaftaran->sertif_kepengurusan) ? 'green' : 'red'}}-600 text-xs">{{!empty(auth()->user()->pendaftaran->sertif_kepengurusan) ? 'Sudah' : 'Belum'}} Upload</div>
                                    </div>
                                </div>
                                <div class="flex items-center mt-5">
                                    <div class="file"> <a href="" class="w-12 file__icon file__icon--empty-directory"></a> </div>
                                    <div class="ml-4">
                                        <a class="font-medium" href="">Foto Kartu Tanda Mahasiswa</a> 
                                        <div class="text-{{!empty(auth()->user()->pendaftaran->foto_ktm) ? 'green' : 'red'}}-600 text-xs">{{!empty(auth()->user()->pendaftaran->foto_ktm) ? 'Sudah' : 'Belum'}} Upload</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- END: Latest Uploads -->
                    </div>

                    <div class="col-span-12 sm:col-span-6 lg:col-span-6">
                        <!-- BEGIN: New Products -->
                        <div class="intro-y box col-span-6">
                            <div class="flex items-center px-5 py-3 border-b border-gray-200">
                                <h2 class="font-medium text-base mr-auto">
                                    Informasi
                                </h2>
                                <button data-carousel="new-products" data-target="prev" class="slick-navigator button px-2 border text-white relative flex items-center text-gray-700 mr-2"> <i data-feather="chevron-left" class="w-4 h-4"></i> </button>
                                <button data-carousel="new-products" data-target="next" class="slick-navigator button px-2 border text-white relative flex items-center text-gray-700"> <i data-feather="chevron-right" class="w-4 h-4"></i> </button>
                            </div>
                            <div class="slick-carousel py-5" id="new-products">
                                @foreach($data['informasi'] as $informasi)
                                <div class="px-5">
                                    <div class="flex flex-col lg:flex-row items-center pb-5">
                                        <div class="flex flex-col sm:flex-row items-center pr-5 lg:border-r border-gray-200">
                                            <div class="sm:mr-5">
                                                <div class="w-20 h-20 image-fit">
                                                    <img  class="rounded-full" src="{{url('dist/images/megaphone.png')}}">
                                                </div>
                                            </div>
                                            <div class="mr-auto text-center sm:text-left mt-3 sm:mt-0">
                                                <a href="" class="font-medium text-lg">{{$informasi->judul}}</a> 
                                                <div class="text-gray-600 mt-1 sm:mt-0">{{$informasi->deskripsi}}</div>
                                            </div>
                                        </div>
                                        <div class="w-full lg:w-auto mt-6 lg:mt-0 pt-4 lg:pt-0 flex-1 flex items-center justify-center px-5 border-t lg:border-t-0 border-gray-200">
                                            <button class="button w-20 justify-center block bg-gray-200 text-gray-600 ml-auto">Download</button>
                                        </div>
                                    </div>
                                    <div class="flex flex-col sm:flex-row items-center border-t border-gray-200 pt-5">
                                        <div class="w-full sm:w-auto flex justify-center sm:justify-start items-center border-b sm:border-b-0 border-gray-200 pb-5 sm:pb-0">
                                            <div class="px-3 py-2 bg-theme-14 text-theme-10 rounded font-medium mr-3">{{date('d M Y', strtotime($informasi->created_at))}}</div>
                                            <div class="text-gray-600">Date of Release</div>
                                        </div>
                                    </div>
                                </div>
                                @endforeach
                            </div>
                        </div>
                        <!-- END: New Products -->
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/profile.blade.php
@extends('layouts.app')

@section('content')
    <div class="content" >
        <div class="content">
            <div class="intro-y flex items-center mt-8">
                <h2 class="text-lg font-medium mr-auto">
                    Update Profile
                </h2>
            </div>
            <div class="grid grid-cols-12 gap-6">
                <!-- BEGIN: Profile Menu -->
                <div class="col-span-12 lg:col-span-4 xxl:col-span-3 flex lg:block flex-col-reverse">
                    <div class="intro-y box mt-5">
                        <div class="p-5 border-t border-gray-200">
                            <a class="flex items-center text-theme-1 font-medium" href=""> <i data-feather="user" class="w-4 h-4 mr-2"></i> Account Setting </a>
                        </div>
                    </div>
                </div>
                <!-- END: Profile Menu -->
                <div class="col-span-12 lg:col-span-8 xxl:col-span-9">
                    <!-- BEGIN: Display Information -->
                    <div class="intro-y box lg:mt-5">
                        <div class="flex items-center p-5 border-b border-gray-200">
                            <h2 class="font-medium text-base mr-auto">
                                Account Information
                            </h2>
                        </div>
                        <form method="post" action="{{route('user.update',auth()->user()->id)}}" enctype="multipart/form-data">
                            @method('PUT')
                            @csrf
                            <div class="p-5">
                                <div class="grid grid-cols-12 gap-5">
                                    <div class="col-span-12 xl:col-span-4">
                                        <div class="border border-gray-200 rounded-md p-5">
                                            <div class="w-40 h-40 relative image-fit cursor-pointer zoom-in mx-auto" id="imagePrev">
                                                <img class="rounded-md" alt="Masukkan Foto Profile" src="{{url('upload/'.auth()->user()->img_profile)}}">
                                                <div title="Foto Profile" class="tooltip w-5 h-5 flex items-center justify-center absolute rounded-full text-white bg-theme-6 right-0 top-0 -mr-2 -mt-2"> <i data-feather="x" class="w-4 h-4"></i> </div>
                                            </div>
                                            <div class="w-40 mx-auto cursor-pointer relative mt-5">
                                                <button type="button" class="button w-full bg-theme-1 text-white">Change Photo</button>
                                                <input type="file" class="w-full h-full top-0 left-0 absolute opacity-0" name="imgProfile" id="imageInput">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-span-12 xl:col-span-8">
                                        <div>
                                            <label>Name</label>
                                            <input type="text" class="input w-full border bg-gray-100 cursor-not-allowed mt-2" placeholder="Input text" value="{{auth()->user()->name}}" disabled>
                                        </div>
                                        <div class="mt-3">
                                            <div>
                                                <label>Email</label>
                                                <input type="text" class="input w-full border bg-gray-100 cursor-not-allowed mt-2" placeholder="Input text" value="{{auth()->user()->email}}" disabled>
                                            </div>
                                        </div>
                                        <div class="mt-3">
                                            <div>
                                                <label>Password</label>
                                                <input type="password" class="input w-full border bg-white mt-2" placeholder="New Password" value="" name="password" >
                                            </div>
                                        </div>
                                        <div class="mt-3">
                                            <div>
                                                <label>Confirm Password</label>
                                                <input type="password" class="input w-full border bg-white mt-2" placeholder="Confirm New Password" value="" name="confirmpassword" >
                                            </div>
                                        </div>
                                        {{-- <a href="{{url('/pengguna')}}" class="button h-20 bg-gray-700 text-white mt-3 mr-2">Kembali</a>
                                        <button type="submit" class="button w-20 h-9 bg-theme-1 text-white mt-3">Save</button> --}}
                                        <div class="col-span-6 mt-3">
                                            <div class="flex justify-start">
                                                <a href="{{url('/pengguna')}}" class="button text-white bg-gray-600 shadow-md mr-2">Kembali</a>
                                                <button type="submit" class="button text-white bg-theme-1 shadow-md mr-2">Simpan</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> 
                        </form>
                    </div>
                    <!-- END: Display Information -->
                </div>
            </div>
        </div>
    </div>

    <script>
        const imageInput = document.getElementById('imageInput');
        const imagePreview = document.getElementById('imagePrev');

        imageInput.addEventListener('change', function(event) {
            const file = event.target.files[0];
            
            if (file) {
                const reader = new FileReader();
                
                reader.onload = function(e) {
                    const img = document.createElement('img');
                    img.src = e.target.result;
                    imagePreview.innerHTML = '';
                    imagePreview.appendChild(img);
                }
                
                reader.readAsDataURL(file);
            }
        }); 
    </script>
@endsection

resources/views/user_dashboard.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
    <div class="grid grid-cols-12 gap-6">
    </div>
</div>
@endsection