routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::resource('/pengguna', UserController::class);
Route::resource('/user', UserController::class);
Route::resource('/informasi', InformasiController::class);
Route::resource('/ormawa', OrmawaController::class);
Route::resource('/pendaftaran', PendaftaranController::class);
Route::resource('/pendaftaran/{pendaftaran_id}/prestasi', PrestasiController::class);
Route::resource('/pendaftaran/{pendaftaran_id}/pengalaman', PengalamanController::class);


Route::get('/pendaftaran/{id}/changestatus', 'PendaftaranController@changeStatus')->name('changestatus');

Route::get('/export/{surat}/{type}/{id}', 'PendaftaranController@exportPdf')->name('export');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('/get-status', 'HomeController@getStatus')->name('get-status');
Route::get('/get-type', 'HomeController@getType')->name('get-type');

app/Informasi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Informasi extends Model
{
    //
}

app/Http/Controllers/InformasiController.php
<?php

namespace App\Http\Controllers;

use App\Informasi;
use Illuminate\Http\Request;

class InformasiController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->search;
        $informasis  = Informasi::where('id', '!=', 0);
        if (isset($search) && !empty($search)) {
            $informasis->where('judul', 'like', '%' . $search . '%');
        }
        $informasis = $informasis->paginate(10);
        return view('informasi.index', [
            'informasis' => $informasis,
            'search' => $search
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('informasi.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $informasi = new Informasi();
        $informasi->type = $request->type;
        $informasi->judul = $request->judul;
        $file = '';
        if (isset($request->file)) {
            $file = $this->uploadGambar($request->file);
        }
        $informasi->file = $file;
        $informasi->deskripsi = $request->deskripsi;
        $informasi->save();

        session()->flash('success', 'Data Informasi Berhasil Ditambah!');
        return redirect('/informasi');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Informasi  $informasi
     * @return \Illuminate\Http\Response
     */
    public function show(Informasi $informasi)
    {
        return view('informasi.view', compact('informasi'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Informasi  $informasi
     * @return \Illuminate\Http\Response
     */
    public function edit(Informasi $informasi)
    {
        return view('informasi.edit', compact('informasi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Informasi  $informasi
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Informasi $informasi)
    {
        $informasi->type = $request->type;
        $informasi->judul = $request->judul;
        if (isset($request->file)) {
            $file = $this->uploadGambar($request->file);
            $informasi->gambar = $file;
        }
        $informasi->deskripsi = $request->deskripsi;
        $informasi->save();

        session()->flash('success', 'Data Informasi Berhasil Diubah!');
        return redirect('/informasi');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Informasi  $informasi
     * @return \Illuminate\Http\Response
     */
    public function destroy(Informasi $informasi)
    {
        Informasi::destroy($informasi->id);
        return response()->json([
            'message' => 'Data Informasi Berhasil DiHapus'
        ]);
    }
}

resources/views/informasi/create.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
    <h2 class="intro-y text-lg font-medium mt-10">
        Tambah Informasi
    </h2>
    <div class="grid grid-cols-12 gap-6 mt-5">
        <div class="intro-y col-span-12 flex flex-wrap sm:flex-no-wrap items-center mt-2">
            <div class="hidden md:block mx-auto text-gray-600"></div>
            <div class="w-full sm:w-auto mt-3 sm:mt-0 sm:ml-auto md:ml-0">
            </div>
        </div>
        <!-- BEGIN: Data List -->
        <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        <form action="/informasi" method="post" enctype="multipart/form-data">
            @csrf
            <div class="flex flex-col" >
                <div class="col-span-12 flex">
                    <div class="col-span-4 w-full">
                        <label for="ormawa" class="block text-sm font-medium leading-6 text-gray-900">Type</label>
                        <div class="mt-2">
                            <select name="type" id="" class="select2 block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 h-10">
                                <option value="">-Pilih Type-</option>
                                <option value="Semua">Semua</option>
                                <option value="Bem">Bem</option>
                                <option value="Balma">Balma</option>
                                <option value="Hima">Hima</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-span-4 w-full mx-2">
                        <label for="judul" class="block text-sm font-medium leading-6 text-gray-900">Judul</label>
                        <div class="mt-2">
                            <input id="judul" name="judul" type="text" placeholder="Masukkan Judul" autocomplete="judul" class="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 h-10">
                        </div>
                    </div>
                    <div class="col-span-4 w-full">
                        <label for="file" class="block text-sm font-medium leading-6 text-gray-900">File</label>
                        <div class="mt-2">
                            <input id="file" name="file" type="file" placeholder="Masukkan Nama Ormawa" autocomplete="ormawa" class="block w-full bg-white rounded-md border-0 py-1 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 h-10">
                        </div>
                    </div>
                </div>
                <div class="col-span-12 flex mt-2">
                    <div class="col-span-6 w-full">
                        <label for="deskripsi" class="block text-sm font-medium leading-6 text-gray-900">Deskripsi</label>
                        <div class="mt-2">
                            <textarea id="deskripsi" cols="30" rows="5" name="deskripsi" type="text" placeholder="Masukkan Deskripsi" autocomplete="deskripsi" class="block w-full rounded-md border-0 py-2 px-4 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"></textarea>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="col-span-6">
            <div class="flex justify-start">
                <a href="{{url('/informasi')}}" class="button text-white bg-gray-600 shadow-md mr-2">Kembali</a>
                <button type="submit" class="button text-white bg-theme-1 shadow-md mr-2">Simpan</button>
            </div>
        </div>
        </form>
</div>
@endsection

resources/views/informasi/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
    <h2 class="intro-y text-lg font-medium mt-10">
        Edit Informasi
    </h2>
    <div class="grid grid-cols-12 gap-6 mt-5">
        <div class="intro-y col-span-12 flex flex-wrap sm:flex-no-wrap items-center mt-2">
            <div class="hidden md:block mx-auto text-gray-600"></div>
            <div class="w-full sm:w-auto mt-3 sm:mt-0 sm:ml-auto md:ml-0">
            </div>
        </div>
        <!-- BEGIN: Data List -->
        <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        <form action="{{route('informasi.update',$informasi->id)}}" method="post" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="flex flex-col" >
                <div class="col-span-12 flex">
                    <div class="col-span-4 w-full">
                        <label for="ormawa" class="block text-sm font-medium leading-6 text-gray-900">Type</label>
                        <div class="mt-2">
                            <select name="type" id="" class="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 h-10">
                                <option value="">-Pilih Type-</option>
                                <option value="Semua" {{$informasi->type == 'Semua' ? 'selected' : ''}}>Semua</option>
                                <option value="Bem" {{$informasi->type == 'Bem' ? 'selected' : ''}}>Bem</option>
                                <option value="Balma" {{$informasi->type == 'Balma' ? 'selected' : ''}}>Balma</option>
                                <option value="Hima" {{$informasi->type == 'Hima' ? 'selected' : ''}}>Hima</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-span-4 w-full mx-2">
                        <label for="judul" class="block text-sm font-medium leading-6 text-gray-900">Judul</label>
                        <div class="mt-2">
                            <input id="judul" value="{{$informasi->judul}}" name="judul" type="text" placeholder="Masukkan Judul" autocomplete="judul" class="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 h-10">
                        </div>
                    </div>
                    <div class="col-span-4 w-full">
                        <label for="file" class="block text-sm font-medium leading-6 text-gray-900">File</label>
                        <div class="mt-2 flex">
                            <input id="file" name="file" type="file" placeholder="Masukkan Nama Ormawa" autocomplete="ormawa" class="block w-full bg-white rounded-md border-0 py-1 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 h-10">
                            <a class="flex items-center button button--sm text-white bg-theme-1 h-10 " href="{{ url('upload/'.$informasi->file) }}"> Lihat </a>
                        </div>
                        <i>Isikan jika ingin mengupload ulang file</i>
                    </div>
                </div>
                <div class="col-span-12 flex mt-2">
                    <div class="col-span-6 w-full">
                        <label for="deskripsi" class="block text-sm font-medium leading-6 text-gray-900">Deskripsi</label>
                        <div class="mt-2">
                            <textarea id="deskripsi" cols="30" rows="5" name="deskripsi" type="text" placeholder="Masukkan Deskripsi" autocomplete="deskripsi" class="block w-full rounded-md border-0 py-2 px-4 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">{{$informasi->deskripsi}}</textarea>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="col-span-6">
            <div class="flex justify-start">
                <a href="{{url('/informasi')}}" class="button text-white bg-gray-600 shadow-md mr-2">Kembali</a>
                <button type="submit" class="button text-white bg-theme-1 shadow-md mr-2">Simpan</button>
            </div>
        </div>
        </form>
</div>
@endsection

resources/views/informasi/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
    <h2 class="intro-y text-lg font-medium mt-10">
        Data List Informasi
    </h2>
    <div class="grid grid-cols-12 gap-6 mt-5">
        <div class="intro-y col-span-12 flex flex-wrap sm:flex-no-wrap items-center mt-2">
            @if(auth()->user()->role == 'admin')
                <a href="{{url('/informasi/create')}}" class="button text-white bg-theme-1 shadow-md mr-2">Tambah Data</a>
            @endif
            <div class="hidden md:block mx-auto text-gray-600"></div>
            <div class="w-full sm:w-auto mt-3 sm:mt-0 sm:ml-auto md:ml-0">
                <div class="w-56 relative text-gray-700">
                    <form action="" method="get">
                        <input type="text" name="search" value="{{$search}}" class="input w-56 box pr-10 placeholder-theme-13" placeholder="Search...">
                        <i class="w-4 h-4 absolute my-auto inset-y-0 mr-3 right-0" data-feather="search"></i> 
                    </form>
                </div>
            </div>
        </div>
        <!-- BEGIN: Data List -->
        <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
            <table class="table table-report -mt-2">
                <thead>
                    <tr>
                        <th class="whitespace-no-wrap">INFORMASI</th>
                        <th class="text-center whitespace-no-wrap">TYPE</th>
                        <th class="text-center whitespace-no-wrap">ACTIONS</th>
                    </tr>
                </thead>
                <tbody>
                    @if(count($informasis) > 0)
                        @foreach($informasis as $informasi)
                            <tr class="intro-x">
                                <td>
                                    <a href="{{ route('informasi.show',$informasi->id) }}" class="font-medium whitespace-no-wrap">{{$informasi->judul}}</a> 
                                    <div class="text-gray-600 text-xs whitespace-no-wrap">{{$informasi->deskripsi}}</div>
                                </td>
                                <td class="table-report__action w-56 text-center">
                                    <a href="" class="font-medium whitespace-no-wrap ">{{$informasi->type}}</a> 
                                </td>
                                <td class="table-report__action w-56">
                                    <div class="flex justify-center items-center">
                                        <a class="flex items-center button button--sm text-white bg-theme-1 p-2 m-1" href="{{ route('informasi.show',$informasi->id) }}"> <i data-feather="eye" class="w-4 h-4 mr-1"></i> View </a>
                                        @if(auth()->user()->role == 'admin')
                                            <a class="flex items-center button button--sm text-white bg-theme-12 p-2" href="{{ route('informasi.edit',$informasi->id) }}"> <i data-feather="edit" class="w-4 h-4 mr-1"></i> Edit </a>
                                            <button class="flex items-center button button--sm text-white bg-theme-6 p-2 m-1 delete-data" type="button" data-redirect="informasi" data-id="{{ $informasi->id }}" data-token="{{ csrf_token() }}"> <i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Delete </button>
                                        @endif
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td class="border-b whitespace-no-wrap text-center" colspan="3">Tidak terdapat data informasi</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
        <!-- END: Data List -->
        <!-- BEGIN: Pagination -->
        <div class="intro-y col-span-12 flex flex-wrap sm:flex-row sm:flex-no-wrap items-center">
            {{ $informasis->links('vendor.pagination.default') }}    
        </div>
        <!-- END: Pagination -->
    </div>
</div>
@endsection

resources/views/informasi/view.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
    <h2 class="intro-y text-lg font-medium mt-10">
        Detail Informasi
    </h2>
    <div class="grid grid-cols-12 gap-6 mt-5">
        <div class="intro-y col-span-12 flex flex-wrap sm:flex-no-wrap items-center mt-2">
            <div class="hidden md:block mx-auto text-gray-600"></div>
            <div class="w-full sm:w-auto mt-3 sm:mt-0 sm:ml-auto md:ml-0">
            </div>
        </div>
        <!-- BEGIN: Data List -->
        <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        <form action="/informasi" method="post" enctype="multipart/form-data">
            @csrf
            <div class="flex flex-col" >
                <div class="col-span-12 flex">
                    <div class="col-span-4 w-full">
                        <label for="ormawa" class="block text-sm font-medium leading-6 text-gray-900">Type</label>
                        <div class="mt-2">
                            <select name="type" id="" class="bg-gray-200 block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 h-10" disabled>
                                <option value="">-Pilih Type-</option>
                                <option value="Semua" {{$informasi->type == 'Semua' ? 'selected' : ''}}>Semua</option>
                                <option value="Bem" {{$informasi->type == 'Bem' ? 'selected' : ''}}>Bem</option>
                                <option value="Balma" {{$informasi->type == 'Balma' ? 'selected' : ''}}>Balma</option>
                                <option value="Hima" {{$informasi->type == 'Semua' ? 'selected' : ''}}>Hima</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-span-4 w-full mx-2">
                        <label for="judul" class="block text-sm font-medium leading-6 text-gray-900">Judul</label>
                        <div class="mt-2">
                            <input id="judul" name="judul" type="text" placeholder="Masukkan Judul" autocomplete="judul" value="{{$informasi->judul}}" class="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset bg-gray-200 ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 h-10" readonly>
                        </div>
                    </div>
                </div>
                <div class="col-span-12 flex mt-2">
                    <div class="col-span-6 w-full">
                        <label for="deskripsi" class="block text-sm font-medium leading-6 text-gray-900">Deskripsi</label>
                        <div class="mt-2">
                            <textarea id="deskripsi" cols="30" rows="5" name="deskripsi" type="text" placeholder="Masukkan Deskripsi" autocomplete="deskripsi" class="block w-full rounded-md border-0 py-2 px-4 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 bg-gray-200" readonly>{{$informasi->deskripsi}}</textarea>
                        </div>
                    </div>
                </div>
                <div class="col-span-12 flex mt-2">
                    <div class="col-span-4 w-full">
                        <label for="file" class="block text-sm font-medium leading-6 text-gray-900">File</label>
                        <div class="mt-2">
                            <div class="w-20 h-20">
                                <i data-feather="file" class="mr-1 w-full h-full"></i>
                            </div>
                            <a class="flex items-center button button--sm text-white bg-theme-1 p-2 m-1 w-16" href="{{url('upload/'.$informasi->file)}}" target="_blank"> <i data-feather="eye" class="w-4 h-4 mr-1"></i> Lihat </a>
                            {{-- <input id="file" name="file" type="file" placeholder="Masukkan Nama Ormawa" autocomplete="ormawa" class="block w-full bg-white rounded-md border-0 py-1 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 h-10"> --}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-span-6">
            <div class="flex justify-start">
                <a href="{{url('/informasi')}}" class="button text-white bg-gray-600 shadow-md mr-2">Kembali</a>
                {{-- <button type="submit" class="button text-white bg-theme-1 shadow-md mr-2">Simpan</button> --}}
            </div>
        </div>
        </form>
</div>
@endsection