routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::resource('/pengguna', UserController::class);
Route::resource('/user', UserController::class);
Route::resource('/informasi', InformasiController::class);
Route::resource('/ormawa', OrmawaController::class);
Route::resource('/pendaftaran', PendaftaranController::class);
Route::resource('/pendaftaran/{pendaftaran_id}/prestasi', PrestasiController::class);
Route::resource('/pendaftaran/{pendaftaran_id}/pengalaman', PengalamanController::class);


Route::get('/pendaftaran/{id}/changestatus', 'PendaftaranController@changeStatus')->name('changestatus');

Route::get('/export/{surat}/{type}/{id}', 'PendaftaranController@exportPdf')->name('export');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('/get-status', 'HomeController@getStatus')->name('get-status');
Route::get('/get-type', 'HomeController@getType')->name('get-type');

app/Ormawa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ormawa extends Model
{
    public function pendaftaran()
    {
        return $this->hasMany(Pendaftaran::class);
    }
}

app/Http/Controllers/OrmawaController.php
<?php

namespace App\Http\Controllers;

use App\Ormawa;
use Illuminate\Http\Request;

class OrmawaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->search;
        $ormawas  = Ormawa::where('id', '!=', 0);
        if (isset($search) && !empty($search)) {
            $ormawas->where('ormawa', 'like', '%' . $search . '%');
        }
        $ormawas = $ormawas->paginate(10);
        return view('ormawa.index', [
            'ormawas' => $ormawas,
            'search' => $search
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('ormawa.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $ormawa = new Ormawa();
        $ormawa->ormawa = $request->ormawa;
        $ormawa->save();

        session()->flash('success', 'Data Ormawa Berhasil Ditambah!');
        return redirect('/ormawa');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Ormawa  $ormawa
     * @return \Illuminate\Http\Response
     */
    public function show(Ormawa $ormawa)
    {
        return view('ormawa.view', compact('ormawa'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Ormawa  $ormawa
     * @return \Illuminate\Http\Response
     */
    public function edit(Ormawa $ormawa)
    {
        return view('ormawa.edit', compact('ormawa'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Ormawa  $ormawa
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ormawa $ormawa)
    {
        $ormawa->ormawa = $request->ormawa;
        $ormawa->save();

        session()->flash('success', 'Data Ormawa Berhasil Diubah!');
        return redirect('/ormawa');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ormawa  $ormawa
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ormawa $ormawa)
    {
        Ormawa::destroy($ormawa->id);
        return response()->json([
            'message' => 'Data Ormawa Berhasil Dihapus'
        ]);
    }
}

resources/views/ormawa/create.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
    <h2 class="intro-y text-lg font-medium mt-10">
        Tambah Ormawa
    </h2>
    <div class="grid grid-cols-12 gap-6 mt-5">
        <div class="intro-y col-span-12 flex flex-wrap sm:flex-no-wrap items-center mt-2">
            <div class="hidden md:block mx-auto text-gray-600"></div>
            <div class="w-full sm:w-auto mt-3 sm:mt-0 sm:ml-auto md:ml-0">
            </div>
        </div>
        <!-- BEGIN: Data List -->
        <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        <form action="/ormawa" method="post">
            @csrf
            <div class="flex flex-col" >
                <label for="ormawa" class="block text-sm font-medium leading-6 text-gray-900">Nama Ormawa</label>
                    <div class="mt-2">
                        <input id="ormawa" name="ormawa" type="ormawa" placeholder="Masukkan Nama Ormawa" autocomplete="ormawa" class="block w-1/2 rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 h-10">
                    </div>
                </div>
            </div>
            <div class="col-span-6">
                <div class="flex justify-start">
                    <a href="{{url('/ormawa')}}" class="button text-white bg-gray-600 shadow-md mr-2">Kembali</a>
                    <button type="submit" class="button text-white bg-theme-1 shadow-md mr-2">Simpan</button>
                </div>
            </div>
        </form>
</div>
@endsection

resources/views/ormawa/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
    <h2 class="intro-y text-lg font-medium mt-10">
        Edit Ormawa
    </h2>
    <div class="grid grid-cols-12 gap-6 mt-5">
        <div class="intro-y col-span-12 flex flex-wrap sm:flex-no-wrap items-center mt-2">
            <div class="hidden md:block mx-auto text-gray-600"></div>
            <div class="w-full sm:w-auto mt-3 sm:mt-0 sm:ml-auto md:ml-0">
            </div>
        </div>
        <!-- BEGIN: Data List -->
        <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        <form action="{{route('ormawa.update',$ormawa->id)}}" method="post">
            @method('PUT')
            @csrf
            <div class="flex flex-col" >
                <label for="ormawa" class="block text-sm font-medium leading-6 text-gray-900">Nama Ormawa</label>
                    <div class="mt-2">
                        <input id="ormawa" name="ormawa" type="ormawa" value="{{$ormawa->ormawa}}" placeholder="Masukkan Nama Ormawa" autocomplete="ormawa" class="block w-1/2 rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 h-10">
                    </div>
                </div>
            </div>
            <div class="col-span-6">
                <div class="flex justify-start">
                    <a href="{{url('/ormawa')}}" class="button text-white bg-gray-600 shadow-md mr-2">Kembali</a>
                    <button type="submit" class="button text-white bg-theme-1 shadow-md mr-2">Simpan</button>
                </div>
            </div>
        </form>
</div>
@endsection

resources/views/ormawa/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
    <h2 class="intro-y text-lg font-medium mt-10">
        Data List Ormawa
    </h2>
    <div class="grid grid-cols-12 gap-6 mt-5">
        <div class="intro-y col-span-12 flex flex-wrap sm:flex-no-wrap items-center mt-2">
            <a href="{{url('/ormawa/create')}}" class="button text-white bg-theme-1 shadow-md mr-2">Tambah Data</a>
            <div class="hidden md:block mx-auto text-gray-600"></div>
            <div class="w-full sm:w-auto mt-3 sm:mt-0 sm:ml-auto md:ml-0">
                
                <div class="w-56 relative text-gray-700">
                    <form action="" method="get">
                        <input type="text" name="search" value="{{$search}}" class="input w-56 box pr-10 placeholder-theme-13" placeholder="Search...">
                        <i class="w-4 h-4 absolute my-auto inset-y-0 mr-3 right-0" data-feather="search"></i> 
                    </form>
                </div>
            </div>
        </div>
        <!-- BEGIN: Data List -->
        <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
            <table class="table table-report -mt-2">
                <thead>
                    <tr>
                        <th class="whitespace-no-wrap">NAMA ORMAWA</th>
                        <th class="text-center flex justify-end items-center whitespace-no-wrap mr-20">ACTIONS</th>
                    </tr>
                </thead>
                <tbody>
                    @if(count($ormawas) > 0)
                        @foreach($ormawas as $ormawa)
                            <tr class="intro-x">
                                <td class="w-40">
                                    <h1 class="text-base" >{{$ormawa->ormawa}}</h1>
                                </td>
                                <td class="table-report__action w-56">
                                    <div class="flex justify-end items-center">
                                        <a class="flex items-center button button--sm text-white bg-theme-1 p-2" href="{{ route('ormawa.show',$ormawa->id) }}"> <i data-feather="eye" class="w-4 h-4 mr-1"></i> View </a>
                                        <a class="flex items-center button button--sm text-white bg-theme-12 ml-1 p-2" href="{{ route('ormawa.edit',$ormawa->id) }}"> <i data-feather="edit" class="w-4 h-4 mr-1"></i> Edit </a>
                                        <button class="flex items-center button button--sm text-white bg-theme-6 p-2 m-1 delete-data" type="button" data-redirect="ormawa" data-id="{{ $ormawa->id }}" data-token="{{ csrf_token() }}"> <i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Delete </button>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td class="border-b whitespace-no-wrap text-center" colspan="2">Tidak terdapat data ormawa</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
        <!-- END: Data List -->
        <!-- BEGIN: Pagination -->
        <div class="intro-y col-span-12 flex flex-wrap sm:flex-row sm:flex-no-wrap items-center">
            {{-- {{ $users->links('vendor.pagination.default') }}     --}}
        </div>
        <!-- END: Pagination -->
    </div>
</div>
@endsection

resources/views/ormawa/view.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
    <h2 class="intro-y text-lg font-medium mt-10">
        Tambah Ormawa
    </h2>
    <div class="grid grid-cols-12 gap-6 mt-5">
        <div class="intro-y col-span-12 flex flex-wrap sm:flex-no-wrap items-center mt-2">
            <div class="hidden md:block mx-auto text-gray-600"></div>
            <div class="w-full sm:w-auto mt-3 sm:mt-0 sm:ml-auto md:ml-0">
            </div>
        </div>
        <!-- BEGIN: Data List -->
        <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        <form action="/ormawa" method="post">
            @csrf
            <div class="flex flex-col" >
                <label for="ormawa" class="block text-sm font-medium leading-6 text-gray-900">Nama Ormawa</label>
                    <div class="mt-2">
                        <input id="ormawa" name="ormawa" value="{{$ormawa->ormawa}}" type="ormawa" placeholder="Masukkan Nama Ormawa" autocomplete="ormawa" class="block w-1/2 rounded-md border-0 py-1.5 px-2 text-gray-700 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 h-10 bg-gray-200" readonly>
                    </div>
                </div>
            </div>
            <div class="col-span-6">
                <div class="flex justify-start">
                    <a href="{{url('/ormawa')}}" class="button text-white bg-gray-600 shadow-md mr-2">Kembali</a>
                </div>
            </div>
        </form>
</div>
@endsection