routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::resource('/pengguna', UserController::class);
Route::resource('/user', UserController::class);
Route::resource('/informasi', InformasiController::class);
Route::resource('/ormawa', OrmawaController::class);
Route::resource('/pendaftaran', PendaftaranController::class);
Route::resource('/pendaftaran/{pendaftaran_id}/prestasi', PrestasiController::class);
Route::resource('/pendaftaran/{pendaftaran_id}/pengalaman', PengalamanController::class);


Route::get('/pendaftaran/{id}/changestatus', 'PendaftaranController@changeStatus')->name('changestatus');

Route::get('/export/{surat}/{type}/{id}', 'PendaftaranController@exportPdf')->name('export');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('/get-status', 'HomeController@getStatus')->name('get-status');
Route::get('/get-type', 'HomeController@getType')->name('get-type');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function pendaftaran()
    {
        return $this->hasOne(Pendaftaran::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->search;
        $users  = User::where('role', 'user');
        if (isset($search) && !empty($search)) {
            $users->where('name', 'like', '%' . $search . '%')->orWhere('email', 'like', '%' . $search . '%');
        }
        $users = $users->paginate(10);
        return view('user.index', [
            'users' => $users,
            'search' => $search
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('user.view', ['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('profile');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find(auth()->user()->id);
        if (!empty($request->password) && !empty($request->confirmpassword)) {
            if ($request->password == $request->confirmpassword) {
                $user->password = bcrypt($request->password);
            } else {
                session()->flash('warning', 'Password Tidak Sama!');
                return redirect('/profile/' . $id);
            }
        }
        $profilfoto = '';
        if (isset($request->imgProfile)) {
            $profilfoto = $this->uploadGambar($request->imgProfile);
            $user->img_profile = $profilfoto;
        }
        $user->save();

        session()->flash('success', 'Berhasil Memperbaharui Profile');

        return redirect('/user');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);
        return response()->json(['message' => 'Data User Berhasil Dihapus!']);
    }
}

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
    <h2 class="intro-y text-lg font-medium mt-10">
        Data List Pengguna
    </h2>
    <div class="grid grid-cols-12 gap-6 mt-5">
        <div class="intro-y col-span-12 flex flex-wrap sm:flex-no-wrap items-center mt-2">
            <!-- <button class="button text-white bg-theme-1 shadow-md mr-2">Tambah Data</button> -->
            <div class="hidden md:block mx-auto text-gray-600"></div>
            <div class="w-full sm:w-auto mt-3 sm:mt-0 sm:ml-auto md:ml-0">
                <div class="w-56 relative text-gray-700">
                    <form action="" method="get">
                        <input type="text" name="search" value="{{$search}}" class="input w-56 box pr-10 placeholder-theme-13" placeholder="Search...">
                        <i class="w-4 h-4 absolute my-auto inset-y-0 mr-3 right-0" data-feather="search"></i> 
                    </form>
                </div>
            </div>
        </div>
        <!-- BEGIN: Data List -->
        <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
            <table class="table table-report -mt-2">
                <thead>
                    <tr>
                        <th class="whitespace-no-wrap">FOTO</th>
                        <th class="whitespace-no-wrap">USER</th>
                        <th class="text-center whitespace-no-wrap">ACTIONS</th>
                    </tr>
                </thead>
                <tbody>
                    @if(count($users) > 0)
                        @foreach($users as $user)
                            <tr class="intro-x">
                                <td class="w-40">
                                    <div class="flex items-center justify-center">
                                        <div class="w-10 h-10 image-fit zoom-in -ml-5">
                                            <img alt="" class="tooltip rounded-full" src="@if(!empty($user->img_profile)) {{ url('upload/'.$user->img_profile) }} @else {{ url('dist/images/user-default.png') }} @endif" title="Uploaded at 17 July 2021">
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <a href="{{ route('pengguna.show',$user->id) }}" class="font-medium whitespace-no-wrap">{{$user->name}}</a> 
                                    <div class="text-gray-600 text-xs whitespace-no-wrap">{{$user->email}}</div>
                                </td>
                                <td class="table-report__action w-56">
                                    <div class="flex justify-center items-center">
                                        <a class="flex items-center button button--sm text-white bg-theme-1 p-2 m-1" href="{{ route('pengguna.show',$user->id) }}"> <i data-feather="eye" class="w-4 h-4 mr-1"></i> View </a>
                                        <button class="flex items-center button button--sm text-white bg-theme-6 p-2 m-1 delete-data" type="button" data-redirect="pengguna" data-id="{{ $user->id }}" data-token="{{ csrf_token() }}"> <i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Delete </button>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td class="border-b whitespace-no-wrap text-center" colspan="3">Tidak terdapat data user</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
        <!-- END: Data List -->
        <!-- BEGIN: Pagination -->
        <div class="intro-y col-span-12 flex flex-wrap sm:flex-row sm:flex-no-wrap items-center">
            {{ $users->links('vendor.pagination.default') }}    
        </div>
        <!-- END: Pagination -->
    </div>
</div>
@endsection

resources/views/user/view.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
    <h2 class="intro-y text-lg font-medium mt-10">
        View Pengguna
    </h2>
    <div class="grid grid-cols-12 gap-6">
        <div class="col-span-12 lg:col-span-12 xxl:col-span-12">
            <!-- BEGIN: Display Information -->
            <div class="intro-y box lg:mt-5">
                <div class="flex items-center p-5 border-b border-gray-200">
                    <h2 class="font-medium text-base mr-auto">
                        Display Information
                    </h2>
                </div>
                <div class="p-5">
                    <div class="grid grid-cols-12 gap-5">
                        <div class="col-span-12 xl:col-span-4">
                            <div class="border border-gray-200 rounded-md p-5">
                                <div class="w-40 h-40 relative image-fit cursor-pointer zoom-in mx-auto">
                                    <img class="rounded-md" alt="Midone Tailwind HTML Admin Template" src="{{!empty($user->img_profile) ? url('upload/'.$user->img_profile) : url('dist/images/user-default.png')}}">
                                    <!-- <div title="Remove this profile photo?" class="tooltip w-5 h-5 flex items-center justify-center absolute rounded-full text-white bg-theme-6 right-0 top-0 -mr-2 -mt-2"> <i data-feather="x" class="w-4 h-4"></i> </div> -->
                                </div>
                                <div class="w-40 mx-auto cursor-pointer relative mt-5">
                                    <!-- <button type="button" class="button w-full bg-theme-1 text-white">Change Photo</button> -->
                                    <input type="file" class="w-full h-full top-0 left-0 absolute opacity-0">
                                </div>
                            </div>
                        </div>
                        <div class="col-span-12 xl:col-span-8">
                            <div>
                                <label>Username</label>
                                <input type="text" class="input w-full border bg-gray-200 cursor-not-allowed mt-2" placeholder="Input text" value="{{$user->name}}" disabled>
                            </div>
                            <div class="mt-3">
                                <label>Email</label>
                                <input type="text" class="input w-full border bg-gray-200 cursor-not-allowed mt-2" placeholder="Input text" value="{{$user->email}}" disabled>
                            </div>
                            <div class="mt-3">
                                <label>Register pada</label>
                                <input type="text" class="input w-full border bg-gray-200 cursor-not-allowed mt-2" placeholder="Input text" value="{{date('d M Y', strtotime($user->created_at))}}" disabled>
                            </div>
                            <a href="/pengguna" type="button" class="button w-20 bg-theme-1 text-white mt-3">Kembali</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END: Display Information -->
        </div>
    </div>
</div>
@endsection